name: EcBarko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_screenutil: ^5.9.3
  flutter_vector_icons: ^2.0.0
  google_sign_in: ^5.2.3
  intl: ^0.18.1
  http: ^0.13.6
  mongo_dart: ^0.8.0
  image_picker: ^1.0.4
  bootstrap_icons: ^1.10.0
  loading_animation_widget: ^1.2.0
  pdf: ^3.10.7 # or the latest version
  printing: ^5.12.0 # or the latest version
  curved_navigation_bar: ^1.0.6
  dropdown_search: ^5.0.6
  qr_flutter: ^4.1.0


  # flutter_vibrate: ^1.3.0
  # audioplayers: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: 0.14.3  # Ensure this line is present
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    # - assets/sounds/flip.mp3
  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf 
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.TTF 
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # Specify your image here
  # android_icon: "launcher_icon"  # Customizable
  # ios_icon: "AppIcon"  # Customizable
  # web: false
